### ISSUE TITLE
set Accept header to application/xml

### ISSUE THREAD

**Issue by ahildebrand** [mganss/IS24RestApi#11]
As the SDK rely on XML content during deserialization of API responses the RestSharp connection must set the Accept header explicitly to application/xml.

**Comment by mganss** [comment]
This is already there, see https://github.com/mganss/IS24RestApi/blob/35db2f43fbccfc6d36df3175026dcdc12ae28fb4/IS24RestApi/IS24Connection.cs#L172-L173

Are you using the latest version?

**Comment by ahildebrand** [comment]
Thanks for the quick reply. 

It's not possible to say which version the customer is using as the UserAgent header field does not provide information about the version of the SDK (UserAgent is set to 'RestSharp 104.3.3.0')
