### ISSUE TITLE
Update to NetStandard 2.0

### ISSUE THREAD

**Issue by ststeiger** [mganss/IS24RestApi#14]
Please update to NetStandard 2.0. 
The dependency RestShard is out of date.

**Comment by mganss** [comment]
In progress on the netstandard branch.

**Comment by ststeiger** [comment]
Why does that take so long ? 
All you need to do is download the sourcecode of the restsharp-version that has been used at the time, and copy the contents into a netstandard2 solution, then add that to the master branch, and basically finished. Optionally copy the contents into a shared project, and add a project that references the shared for each supported framework, like net4, netstandard2, etc.  Then do the same to IS24RestAPI.

**Comment by setoy** [comment]
Then why don't you do that? It's Open Source for a reason.

**Comment by mganss** [comment]
There may be a misconception that this project is a corporate service of Immobilienscout24. This is not the case, it's a spare time effort by the contributors, including myself.

I don't want to use an older version of RestSharp, much less copy their source code into this project. They changed their API, so this means the approach used for testing (`IHttp` stub) doesn't work anymore. I had toyed with the idea of replacing RestSharp altogether, but opted for a different approach (`IRestClient` stub).

**Comment by ststeiger** [comment]
Aaah, ok, that explains it. 
Well, i tried with the latest version of restsharp, too, but found it too much work, so I opted for the old version. 
RestSharp is an ever changing project - if you update now, you'll have to update later anyway. 
They always break backwards compatibility here and there. 
I'd remove it completely. 
All you really need is the OAuth stuff.

**Comment by Falco20019** [comment]
I lately use https://github.com/canton7/RestEase as an alternative to RestSharp as I find it easier and cleaner to use. So maybe that’s also something to have a look at.

**Comment by mganss** [comment]
Finished. 3.0.57-beta supports (only) netstandard2.0.

Using the current RestSharp seemed like the easiest path for now, considering this is not a project I can invest too much time in (already took me a whole lot longer than I had anticipated 🙄 ).

@Falco20019 RestEase looks nice, as does [Refit](https://github.com/reactiveui/refit) which it is inspired by. One thing that concerns me with RestEase is that they state:
> It won't work on platforms which don't support runtime code generation, including .NET Native and iOS.

Refit doesn't seem to have this problem as they explicitly mention support for Xamarin.iOS, although they also seem to generate classes that implement interfaces you supply 🤷‍♂️ 

If anyone wants to pick up replacing RestSharp with something else (ideally just plain old `HttpClient`), I'd be grateful.
